parameters:
#    srs_event.example.class: Srs\EventBundle\Example

services:
#    srs_event.example:
#        class: %srs_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
