parameters:
#    srs_home.example.class: Srs\HomeBundle\Example

services:
#    srs_home.example:
#        class: %srs_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
