parameters:
#    srs_news.example.class: Srs\NewsBundle\Example

services:
#    srs_news.example:
#        class: %srs_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
