<?php

namespace Srs\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getTwoLastNews()
    {
        //$qb = $em->createQuery('SELECT n FROM news n ORDER BY n.dateCreation DESC');
        
        $qb = $this->_em->createQueryBuilder();

        $qb->select('n')
           ->from('SrsNewsBundle:News', 'n')
           ->orderBy('n.dateCreation', 'DESC')
           ->setMaxResults(2);
        
        return $qb->getQuery()
               ->getResult();
    }
    
    public function getByTags(array $nameTags)
    {
        $qb = $this->createQueryBuilder('n');

        $qb ->join('n.tags', 't')
            ->where($qb->expr()->in('t.name', $nameTags)); // Puis on filtre sur le nom des tags.

        return $qb->getQuery()
                   ->getResult();
    }
    public function getDistinctNameTag(){
        $qb = $this->_em->createQueryBuilder();

        $qb->select('t.1')
           ->distinct()
           ->from('SrsTagBundle:Tag', 't');
        
        return $qb->getQuery()
               ->getResult();
    }
}
