<?php

namespace Srs\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getNewsByTag($name)
    {
        /*$qb = $this->_em->createQuery("SELECT n.title, n.body
                                   FROM SrsNewsBundle:News n, news_tag nt, tag t
                                   WHERE n.id = nt.news_id
                                   AND nt.tag_id = t.id
                                   AND t.name = ':name'");
        
        $qb->setParameter(':name', $name);

        return $qb->getResult();*/
    }
}
