parameters:
#    srs_comment.example.class: Srs\CommentBundle\Example

services:
#    srs_comment.example:
#        class: %srs_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
